config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  devise_scope :user do
    match '/users/confirmation', to: 'users/confirmations#update', via: :put
  end

  authenticated :user do
    root to: redirect('/events'), as: :authenticated_user
  end

  get 'orders/event/:event_slug', to: 'orders#new'
  get '/events/:event_slug/orders', to: 'orders#new', as: :event_ticket_order
  get '/events/new_ticket', to: 'events#new_ticket'
  get '/events/save_ticket', to: 'events#save_ticket'
  resources :events, param: :slug do
    put 'update_slug', to: 'events#update_slug'
    get 'open_close_registration'
    get 'overview'
    resources :orders do
      member do
        get 'attendees/new', to: 'orders#attendee_form', as: :order_attendee_form
        post 'attendees', to: 'orders#submit_attendee'
        get 'attendees_confirmation', to: 'orders#attendees_confirmation'
        get 'payment_methods', to: 'orders#payment_methods'
        post 'payment_methods', to: 'invoices#create'
        get 'confirmation', to: 'orders#confirmation', as: :order_confirmation
        post 'confirmation', to: 'orders#confirm'
        get 'check_out', to: 'orders#check_out', as: :order_check_out
      end
    end
    resources :email_blasts, module: 'events'
    resources :form_custom_fields, module: 'events'
    resources :committees, module: 'events'
    resources :choices, module: 'events'
    resources :attendees, module: 'events' do
      post 'send_manual_confirmation'
      delete 'attendee_delete'
      get 'attend'
    end
    resources :ticket_categories, module: 'events'
    resources :tasks, module: 'events' do
      get 'set_done'
    end
    resources :cashflows, module: 'events'
  end
  resources :assignments do
    match '/accept', to: 'assignments#accept', via: :get
  end
  resources :users
  resources :notifications do
    member do
      match '/mark_as_read', to: 'notifications#mark_as_read', via: :get
    end
  end
  root 'static_pages#home'
  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/terms_and_conditions', to: 'static_pages#terms_and_conditions'
  get '/pricing', to: 'static_pages#pricing'
  get '/features', to: 'static_pages#features'
  get '/about_us', to: 'static_pages#about_us'
  get '/faq', to: 'static_pages#faq'

  namespace :api, path: '/', constraints: { subdomain: 'api' }, defaults: { format: :json } do
    namespace :v1 do
      resources :events, param: :slug do
        resources :attendees do
          collection do
            get '/verify_ticket/:token', to: 'attendees#verify_ticket'
          end
        end
        resources :ticket_categories
      end
      resources :task_lists
      resources :tasks
      resources :authentication, only: [:create]
    end
  end

  get '/my_tasks', to: 'tasks#my_tasks', module: 'events'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get '/attendance_confirmation', to: 'events/attendees#attendance_confirmation'

  get '/tickets/preview', to: 'tickets#preview'
  post '/tickets/send', to: 'tickets#send_ticket'

  post '/payments/verify'
  post '/payments/notify'
  post '/payments/redirect'
  post '/payments/cancel'

  post '/reimbursement', to: 'events/cashflows#submit_reimbursement_request'

  get '/account-setting', to: 'accounts#edit', as: 'account_setting'
  patch '/account-setting', to: 'accounts#update'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  layout 'landing_page'

  def home

  end

  def privacy_policy
  end

  def features
  end

  def terms_and_conditions
  end

  def pricing
  end

  def about_us
  end

end

app/views/static_pages/_static_header.html.erb
<div class="top-bar static-header">
  <div class="top-bar-title">
    <a href="/"><%= image_tag 'logogram-light.png' %></a>
  </div>

  <span data-responsive-toggle="responsive-menu" data-hide-for="large">
    <a class="right-menu-toggle float-right"><%= icon('bars') %></a>
  </span>

  <div id="responsive-menu">
    <div class="top-bar-right">
      <ul class="menu">
        <li><a href="/">Home</a></li>
        <li><a href="<%= features_path %>">Features</a></li>
        <li><a href="<%= pricing_path %>">Pricing</a></li>
        <li><a href="https://medium.com/the-handl-times" target="_blank">Blog</a></li>
        <li><%= link_to 'Log in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/static_pages/about_us.html.erb
<%= render 'static_header' %>

<div class="home-about">
  <div class="row">
    <div class="large-8 large-centered columns">
      <!-- <h1 class="special">About Handl</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hendrerit vehicula lacus, sit amet suscipit est convallis vitae. Quisque pharetra ligula sed vehicula iaculis. Nullam imperdiet placerat felis, viverra volutpat purus consequat in. Morbi auctor quis odio a tincidunt. Etiam eleifend cursus finibus. Donec elementum orci nec mauris efficitur consectetur. Quisque consequat volutpat congue. Duis pharetra dignissim metus et pulvinar.</p> -->

      <h1 class="special">Team Handl</h1>

      <div class="row">
        <div class="large-12 columns">
          <div class="team-member">
            <div class="row">
              <div class="small-6 large-3 columns">
                <div class="avatar">
                  <%= image_tag 'team/about-dito.jpg' %>
                </div>
              </div>

              <div class="small-12 large-9 columns">
                <div class="description">
                  <h2>Dito Cesartista</h2>
                  <h3>Chief Executive Officer</h3>
                  <p>Satu kata untuk Handl: <strong>Perubahan</strong></p>
                  <p>Berbekal ilmu Teknologi Informasi yang dienyamnya di UGM, Dito mengambil peran dan tugas CEO Handl. Dito telah membangun Handl dalam berbagai lini termasuk backend developer, mobile apps, bahkan analisis bisnis. Seorang CEO ialah ia yang memiliki prinsip kuat dalam dirinya dan Dito percaya semua orang bisa melakukan sesuatu asal mau belajar, termasuk dirinya sendiri. “Kalau orang lain bisa sesuatu apapun, aku pasti juga bisa”</p>
                </div>
              </div>
            </div>
          </div>

          <div class="team-member">
            <div class="row">
              <div class="small-6 large-3 columns">
                <div class="avatar">
                  <%= image_tag 'team/about-fahmi.jpg' %>
                </div>
              </div>

              <div class="small-12 large-9 columns">
                <div class="description">
                  <h2>Fahmi Ardhianto</h2>
                  <h3>Chief Technology Officer</h3>
                  <p>Satu kata untuk Handl: <strong>Manfaat</strong></p>
                  <p>Fahmi merupakan kunci penyeimbang ide-ide gila Handl. Dengan sifatnya yang realistis, ia menjadi salah satu co founder Handl. Fahmi telah menginvestasikan banyak hal, terutama pengetahuan programmingnya. Code di balik produk Handl dituliskan dengan baik oleh Fahmi. Kepiawannya merumuskan bahasa pemrogaman membawanya menjadi finalis dalam Compfest Programming Competition 2010, Best pitch on MIT AITI Indonesia 2013, dan menjadi peserta dalam Google Hackfair 2015 Indonesia.</p>
                </div>
              </div>
            </div>
          </div>

          <div class="team-member">
            <div class="row">
              <div class="small-6 large-3 columns">
                <div class="avatar">
                  <%= image_tag 'team/about-reyhan.jpg' %>
                </div>
              </div>

              <div class="small-12 large-9 columns">
                <div class="description">
                  <h2>Reyhan Aditrea</h2>
                  <h3>UI / UX Designer</h3>

                  <div class="social-media">
                    <%= link_to icon('dribbble', class:'fa-2x'), "https://dribbble.com/reyhanaditrea" %>

                    <%= link_to icon('instagram', class:'fa-2x'), "https://www.instagram.com/reyhanaditrea/" %>

                    <%= link_to icon('linkedin-square', class:'fa-2x'), "https://www.linkedin.com/in/reyhanaditrea/" %>
                  </div>

                  <p>Satu kata untuk Handl: <strong>Efisiensi</strong></p>
                  <p>Reyhan adalah think-tanker Handl. Pemikirannya yang dinamis dan kreatif menjadi oase ide brilian dalam produk-produk kami. Bersama Fahmi, Reyhan menjadi pioneer berdirinya Handl dan telah membantu coding dan desain estetis website Handl. “The most important thing in life is TO LIVE”. Prinsip ini yang membawa Reyhan menjajal berbagai hal sebelumnya termasuk menjadi game developer. Saat ini Reyhan telah memiliki akun pribadi di dribbble.com, sebuah komunitas bergengsi bagi desainer.</p>
                </div>
              </div>
            </div>
          </div>

          <div class="team-member">
            <div class="row">
              <div class="small-6 large-3 columns">
                <div class="avatar">
                  <%= image_tag 'team/about-sofi.jpg' %>
                </div>
              </div>

              <div class="small-12 large-9 columns">
                <div class="description">
                  <h2>Sofi Nabila</h2>
                  <h3>Chief HR Officer & Copywriter</h3>

                  <p>Satu kata untuk Handl: <strong>Mimpi</strong></p>
                  <p>Menjadi tukang merangkai kata, Sofi bergabung dalam tim Handl sebagai copywriter. Konten web dan media informasi lain dari Handl menjadi tanggung jawabnya. Sofi merupakan pimpinan redaksi cetak BPPM Equilibrium untuk perioder 2016/2017 dan telah menuliskan beberapa tulisan baik online maupun cetak. Bermodal pengalamannya berinteraksi dengan banyak orang pun kini ia memegang kendali atas manajemen sumber daya manusia dan penjadwalan dalam tim Handl.</p>
                </div>
              </div>
            </div>
          </div>

          <div class="team-member">
            <div class="row">
              <div class="small-6 large-3 columns">
                <div class="avatar">
                  <%= image_tag 'team/about-fiha.jpg' %>
                </div>
              </div>

              <div class="small-12 large-9 columns">
                <div class="description">
                  <h2>Fiha Febiala</h2>
                  <h3>Graphic Designer & Public Relation</h3>

                  <p>Satu kata untuk Handl: <strong>Sukses</strong></p>
                  <p>Berbekal ilmu dari Teknologi Informasi UGM, Fiha bertanggung jawab atas kualitas produk yang dihasilkan Handl. Lebih dari itu, Fiha juga mampu menghasilkan desain-desain kecil pemanis di dalam website kami. Kebanggaannya terhadap Handl pun menjadi jembatan antara kami dan beberapa klien. Saat ini, Fiha memiliki keinginan untuk memperdalam dunia komunikasi guna membantu pemasaran Handl lebih baik lagi.</p>
                </div>
              </div>
            </div>
          </div>

          <div class="team-member">
            <div class="row">
              <div class="small-6 large-3 columns">
                <div class="avatar">
                  <%= image_tag 'team/about-digas.jpg' %>
                </div>
              </div>

              <div class="small-12 large-9 columns">
                <div class="description">
                  <h2>Raden Digas</h2>
                  <h3>Brand Manager</h3>

                  <p>Satu kata untuk Handl: <strong>Bagus</strong></p>
                  <p>Menjalankan peran sebagai Brand Manager Handl, Digas tak lepas dari segala urusan merk termasuk desain dan analisis. Logo Handl adalah salah satu sumbangsih desain terbaiknya dalam perjalanan Handl. Selain branding, digas juga membantu dalam visual guide Handl. Digas saat ini sedang memperdalam ilmunya di Desain Komunikasi Visual ISI, Yogyakarta dan kerap mengikuti beberapa pameran seni. Ia juga memiliki studio desain independen.</p>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

  <div class="static-footer">
    <div class="row">
      <div class="large-5 columns">
        <a href="/" class="logo">
          <%= image_tag 'logogram-light.png' %>
        </a>

        <div class="logo-desc">
          <strong>HANDL</strong> adalah platform untuk membantu manajemen event, khususnya untuk bagian registrasi
        </div>
      </div>

      <div class="large-2 columns">
        <ul>HANDL
          <li><a href="<%= about_us_path %>">About Us</a></li>
        </ul>
      </div>

      <div class="large-2 columns">
        <ul>LEGAL
          <li><a href="<%= terms_and_conditions_path %>">Terms & Conditions</a></li>
          <li><a href="<%= privacy_policy_path %>">Privacy Policy</a></li>
        </ul>
      </div>

      <div class="large-3 columns">
        <ul>CONTACT US
          <li>Jalan Asem Kranji K7 Sekip, UGM, Bulaksumur, Yogyakarta.</li>
          <li>+62 852 10809393</li>
          <li>hi@handl.in</li>
        </ul>
      </div>
    </div>
  </div>

</div>

app/views/static_pages/faq.html.erb
FAQ

app/views/static_pages/features.html.erb
<%= render 'static_header' %>

<div class="home-feature">
  <div class="section-1">
    <div class="row column">
      <h1><strong>Manage</strong> and <strong>control</strong> your event, easily</h1>
      <p>Handl adalah sebuah platform yang memudahkanmu dalam mengorganisir registrasi acara yang ingin kamu adakan.</p>
      <p>Dilengkapi dengan fitur-fitur esensial untuk mengatur segala prosesnya.</p>
      <p>Gunakan Handl untuk meringankan proses perancangan <em>event</em>-mu!</p>

      <%= image_tag 'home-features/all-event.jpg' %>
    </div>
  </div>

  <div class="section-2">
    <%= image_tag 'home-features/bubbles.png', class:'bubbles' %>

    <div class="row">
      <div class="large-4 large-offset-1 columns">
        <h1>Create your event</h1>
        <div style="width:25%; background:#ffffff; height:2px;margin:20px 0;"></div>
        <p>Hal terpenting yang harus kamu lakukan sebelum memulai petualanganmu bersama Handl. Daftarkan <em>event</em> apapun yang ingin kamu laksanakan dalam form yang telah kami sediakan. Kamu bisa memberi segala informasi tentang <em>event</em>mu. Kapan, dimana, siapa, dan apapun</p>
      </div>

    </div>

    <div class="row column">
      <%= image_tag 'home-features/new-event.jpg', class:'screenshoot' %>
    </div>
  </div>

  <div class="section-3">
    <%= image_tag 'home-features/team.jpg' %>

    <div class="row">
      <div class="large-5 large-offset-6 columns">
        <h1>Invite, Collaborate!</h1>
        <div style="float:right;width:25%; background:#009D8E; height:2px;margin:20px 0;"></div>
        <p>Bersama-sama menjadi lebih mudah dalam mengatur registrasi <em>event</em>-mu</p>
        <p>Berkolaborasi dengan optimal bersama Handl</p>
      </div>
    </div>
  </div>

  <div class="section-4">
    <%= image_tag 'home-features/registration.png', class:'screenshoot' %>

    <div class="row">
      <div class="large-6 large-offset-6 columns">
        <%= image_tag 'home-features/blastoff.png', class:'blastoff' %>
        <div style="width:10%; background:#FFFFFF; height:2px;margin:20px 0 20px 100px;"></div>
        <p><em>Event</em>-mu akan mendapatkan halaman khusus dengan link unik dengan sogala informasi tentang <em>event</em>-mu. Dilengkapi dengan formulir registrasi yang terintegrasi. Sebarkan <em>event</em>-mu ke seluruh penjuru dan capai targer <em>full house</em> secepatnya.</p>
      </div>
    </div>
  </div>

  <div class="section-5">
    <%= image_tag 'home-features/form-editor.jpg' %>

    <div class="row">
      <div class="large-5 large-offset-6 columns">
        <h1>Customize Freely</h1>
        <div style="float:right;width:25%; background:#009D8E; height:2px;margin:20px 0;"></div>
        <p>Kami telah menyediakan <em>template</em> untuk formulir pendaftaran berisi nama, alamat e-mail, institusi, dan nomor handphone. Namun, jika kamu membutuhkan informasi lebih, kamu dapat menambahkan kategori lainnya</p>
      </div>
    </div>
  </div>

  <div class="section-6">
    <div class="row">
      <div class="large-4 large-offset-1 columns">
        <h1>Manage your participants</h1>
        <div style="width:25%; background:#333333; height:2px;margin:20px 0;"></div>
        <p>Segala informasi dan seluruh peserta yang telah mendaftar tersimpan dalam <em>database event</em>-mu. Kamu dapat mengakses dan mengaturnya socara bebas.</p>
      </div>

    </div>

    <%= image_tag 'home-features/participant.jpg' %>
  </div>

  <div class="section-7">
    <div class="row column">
      <div class="screenshoot">
        <%= image_tag 'home-features/cashflow.jpg' %>
      </div>

      <h1>Monitor the cashflow</h1>
      <p>kamu dapat mengawasi aliran dana dari <em>event</em>-mu. Segala pemasukkan dari pendaftaran hingga pencairan dana dapat kamu kendalikkan.</p>

    </div>

    <div class="free-section">
      <h1>Free Ticket</h1>
      <p>Kamu dapat bebas menggunakan Handl jika event yang diadakan </br>tidak memungut biaya</p>
    </div>

    <div class="paid-section">
      <h1>Paid Ticket</h1>
      <p>Jika event yang kamu adakan memungut biaya tiket pendaftaran, </br>maka akan ada biaya servis dari kami. <a href="<%= pricing_path %>">Pelajari lebih lanjut</a></p>
    </div>
  </div>

  <div class="row section-8">
    <div class="large-6 large-centered columns">
      <div class="logo">
        <%= image_tag 'logogram-dark.png', class:'illustration' %>
      </div>

      <h3>Handl menawarkan kemudahan dan efisiensi perancangan <em>event</em>-mu</h3>
      <p>Jadilah bagian dari pergerakan menuju kemajuan!<p>
    </div>
  </div>

  <div class="static-footer">
    <div class="row">
      <div class="large-5 columns">
        <a href="/" class="logo">
          <%= image_tag 'logogram-light.png' %>
        </a>

        <div class="logo-desc">
          <strong>HANDL</strong> adalah platform untuk membantu manajemen event, khususnya untuk bagian registrasi
        </div>
      </div>

      <div class="large-2 columns">
        <ul>HANDL
          <li><a href="<%= about_us_path %>">About Us</a></li>
        </ul>
      </div>

      <div class="large-2 columns">
        <ul>LEGAL
          <li><a href="<%= terms_and_conditions_path %>">Terms & Conditions</a></li>
          <li><a href="<%= privacy_policy_path %>">Privacy Policy</a></li>
        </ul>
      </div>

      <div class="large-3 columns">
        <ul>CONTACT US
          <li>Jalan Asem Kranji K7 Sekip, UGM, Bulaksumur, Yogyakarta.</li>
          <li>+62 852 10809393</li>
          <li>hi@handl.in</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="top-bar static-header transparent">
  <div class="top-bar-title">
    <a href="/"><%= image_tag 'logogram-light.png' %></a>
  </div>

  <span data-responsive-toggle="responsive-menu" data-hide-for="large">
    <a class="right-menu-toggle float-right"><%= icon('bars') %></a>
  </span>

  <div id="responsive-menu">
    <div class="top-bar-right">
      <ul class="menu">
        <li><a href="/">Home</a></li>
        <li><a href="<%= features_path %>">Features</a></li>
        <li><a href="<%= pricing_path %>">Pricing</a></li>
        <li><a href="https://medium.com/the-handl-times" target="_blank">Blog</a></li>
        <li><%= link_to 'Log in', new_user_session_path %></li>
      </ul>
    </div>
  </div>
</div>

<div class="landing-page">
  <div id="home">
    <div class="overlay"></div>
    <div class="row">
      <div class="large-7 large-offset-5 columns">
        <h1>Let’s take your event registration to the next level!</h1>
        <p>Dengan cara yang elegan dan praktis, <span>HANDL</span> akan membantumu mendalangi bagian registrasi acara hebatmu.</p>
        <p><span>HANDL</span> adalah sistem manajemen registrasi acara dalam satu portal.</p>
      </div>
    </div>
  </div>

  <div id="features">
    <div class="row column">
      <h1>Naikkan Level Kualitas Acaramu!</h1>
      <h2>Capai efisiensi dan efektivitas dengan fitur HANDL ini:</h2>
    </div>

    <div class="row">
      <div class="large-6 columns">
        <%= image_tag 'home/online.png' %>
        <h3>Terhubung dengan Registrasi Online</h3>
        <p>Peserta dapat langsung melakukan registrasi online pada fitur formulir HANDL dan secara automatis data peserta akan terekap dalam database penyelenggara.</p>
      </div>

      <div class="large-6 columns">
        <%= image_tag 'home/statistic.png' %>
        <h3>Tersedia dengan Auto-Rekap</h3>
        <p>Dokumen daftar hadir peserta, daftar rekap pembayaran, dan lainnya dapat segera kamu dapatkan dengan mengunduhnya di HANDL</p>
      </div>

      <div class="large-6 columns">
        <%= image_tag 'home/payment.png' %>
        <h3>Mendukung Semua Metode Pembayaran</h3>
        <p>Terintegrasi dengan Doku Payment Gateway, berbagai alternatif pembayaran tiket oleh peserta akan terkelola dengan sistem pembayaran yang juga digunakan oleh layanan musik Spotify: aman dan fleksibel</p>
      </div>

      <div class="large-6 columns">
        <%= image_tag 'home/reimburse.png' %>
        <h3>Terpercaya dengan Pencairan 1x24 Jam</h3>
        <p>Uang pembayaran dari peserta dapat segera kamu cairkan dalam sehari melalui HANDL.</p>
      </div>
    </div>

    <div class"row column" style="text-align:center;">
      <a class="button" href="<%= features_path %>">Learn more about features</a>
    </div>
  </div>

  <div id="pricing">
    <div class="row">
      <div class="large-10 large-centered columns">
        <h1>Pricing</h1>
        <h2>Handl memberikan fitur penjualan dan pembayaran tiket secara online. Biaya yang dikenakan untuk servis Handl ini akan langsung dipotong setiap transaksi berhasil.</h2>

        <div class="row">
          <div class="small-12 large-6 columns" style="padding:0 10px;">
            <div class="pricing-container">
              <div class="pricing-box">
                <h3>ACARA GRATIS</h3>
                <div style="width:10%; margin:0 auto 30px; background:#009D8E; height:2px;"></div>

                <h4>IDR <span>0</span></h4>

                <p>Gunakan Handl secara bebas tanpa tambahan biaya untuk kamu yang akan mengadakan acara gratis!</p>
              </div>
            </div>
          </div>

          <div class="small-12 large-6 columns" style="padding:0 10px;">
            <div class="pricing-container">
              <div class="pricing-box">
                <h3>ACARA BERBAYAR</h3>
                <div style="width:10%; margin:0 auto 30px; background:#009D8E; height:2px;"></div>

                <h4>IDR <span id="price-output">0</span> / ticket</h4>

                <div class="row">
                  <div class="large-9 large-centered columns">
                    <form>
                      <div class="with-icon" style="margin-bottom:16px;">
                        <div class="text-on">IDR</div>

                        <input id="price-input" type="number" placeholder="masukkan harga tiketmu..."></input>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class"row column" style="text-align:center;">
      <a class="button" href="<%= pricing_path %>">Learn more about pricing</a>
    </div>
  </div>

  <div id="sign">
    <div class="row">
      <div class="large-6 columns">
        <h1>Mari gunakan cara-cara HANDL!</h1>
        <h2>“Gunakan cara-cara baru dalam menyampaikan informasi, tinggalkan pola-pola lama”</h2>
        <h3>Joko Widodo, Presiden ke-7 Republik Indonesia</h3>

        <a class="button button--white" href="<%= new_user_registration_path %>">Sign up</a>
      </div>

      <div class="large-6 columns" style="text-align:center;">
        <%= image_tag 'home/mac-image.png' %>
      </div>
    </div>

  </div>

  <div class="static-footer">
    <div class="row">
      <div class="large-5 columns">
        <a href="/" class="logo">
          <%= image_tag 'logogram-light.png' %>
        </a>

        <div class="logo-desc">
          <strong>HANDL</strong> adalah platform untuk membantu manajemen event, khususnya untuk bagian registrasi
        </div>
      </div>

      <div class="large-2 columns">
        <ul>HANDL
          <li><a href="<%= about_us_path %>">About Us</a></li>
        </ul>
      </div>

      <div class="large-2 columns">
        <ul>LEGAL
          <li><a href="<%= terms_and_conditions_path %>">Terms & Conditions</a></li>
          <li><a href="<%= privacy_policy_path %>">Privacy Policy</a></li>
        </ul>
      </div>

      <div class="large-3 columns">
        <ul>CONTACT US
          <li>Jalan Asem Kranji K7 Sekip, UGM, Bulaksumur, Yogyakarta.</li>
          <li>+62 852 10809393</li>
          <li>hi@handl.in</li>
        </ul>
      </div>
    </div>
  </div>
</div>

<script charset="utf-8">
  $(".landing-page").scroll(function() {
    var scroll = $(".landing-page").scrollTop();
     //>=, not <=
    if (scroll >= 100) {
        //clearHeader, not clearheader - caps H
        $(".static-header").removeClass('transparent');
        // $('.top-bar-title a img').attr("src" , "<%= asset_path('logo-light.png') %>");
    }
    else{
      $(".static-header").addClass('transparent');
      // $('.top-bar-title a img').attr("src" , "<%= asset_path('logo-dark.png') %>");
    }
  }); //missing );

  function addCommas(nStr){
  	nStr += '';
  	x = nStr.split('.');
  	x1 = x[0];
  	x2 = x.length > 1 ? '.' + x[1] : '';
  	var rgx = /(\d+)(\d{3})/;
  	while (rgx.test(x1)) {
  		x1 = x1.replace(rgx, '$1' + '.' + '$2');
  	}
  	return x1 + x2;
  }

  $("#price-input").keyup(function(){
      var price = $("#price-input").val();
      var output;

      if(price===0){
          output=0;
      }

      else if(price>0 && price <= 100000){
          output= 5000;
      }

      else{
        output=Math.ceil(0.05*price);
        output = addCommas(output);
      }

      console.log(output);

      $("#price-output").html(output);
  });

</script>