config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  devise_scope :user do
    match '/users/confirmation', to: 'users/confirmations#update', via: :put
  end

  authenticated :user do
    root to: redirect('/events'), as: :authenticated_user
  end

  get 'orders/event/:event_slug', to: 'orders#new'
  get '/events/:event_slug/orders', to: 'orders#new', as: :event_ticket_order
  get '/events/new_ticket', to: 'events#new_ticket'
  get '/events/save_ticket', to: 'events#save_ticket'
  resources :events, param: :slug do
    put 'update_slug', to: 'events#update_slug'
    get 'open_close_registration'
    get 'overview'
    resources :orders do
      member do
        get 'attendees/new', to: 'orders#attendee_form', as: :order_attendee_form
        post 'attendees', to: 'orders#submit_attendee'
        get 'attendees_confirmation', to: 'orders#attendees_confirmation'
        get 'payment_methods', to: 'orders#payment_methods'
        post 'payment_methods', to: 'invoices#create'
        get 'confirmation', to: 'orders#confirmation', as: :order_confirmation
        post 'confirmation', to: 'orders#confirm'
        get 'check_out', to: 'orders#check_out', as: :order_check_out
      end
    end
    resources :email_blasts, module: 'events'
    resources :form_custom_fields, module: 'events'
    resources :committees, module: 'events'
    resources :choices, module: 'events'
    resources :attendees, module: 'events' do
      post 'send_manual_confirmation'
      delete 'attendee_delete'
      get 'attend'
    end
    resources :ticket_categories, module: 'events'
    resources :tasks, module: 'events' do
      get 'set_done'
    end
    resources :cashflows, module: 'events'
  end
  resources :assignments do
    match '/accept', to: 'assignments#accept', via: :get
  end
  resources :users
  resources :notifications do
    member do
      match '/mark_as_read', to: 'notifications#mark_as_read', via: :get
    end
  end
  root 'static_pages#home'
  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/terms_and_conditions', to: 'static_pages#terms_and_conditions'
  get '/pricing', to: 'static_pages#pricing'
  get '/features', to: 'static_pages#features'
  get '/about_us', to: 'static_pages#about_us'
  get '/faq', to: 'static_pages#faq'

  namespace :api, path: '/', constraints: { subdomain: 'api' }, defaults: { format: :json } do
    namespace :v1 do
      resources :events, param: :slug do
        resources :attendees do
          collection do
            get '/verify_ticket/:token', to: 'attendees#verify_ticket'
          end
        end
        resources :ticket_categories
      end
      resources :task_lists
      resources :tasks
      resources :authentication, only: [:create]
    end
  end

  get '/my_tasks', to: 'tasks#my_tasks', module: 'events'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get '/attendance_confirmation', to: 'events/attendees#attendance_confirmation'

  get '/tickets/preview', to: 'tickets#preview'
  post '/tickets/send', to: 'tickets#send_ticket'

  post '/payments/verify'
  post '/payments/notify'
  post '/payments/redirect'
  post '/payments/cancel'

  post '/reimbursement', to: 'events/cashflows#submit_reimbursement_request'

  get '/account-setting', to: 'accounts#edit', as: 'account_setting'
  patch '/account-setting', to: 'accounts#update'
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  protect_from_forgery with: :null_session
  layout 'landing_page'

  def verify
    storeid         = params['STOREID']
    transidmerchant = params['TRANSIDMERCHANT']
    amount          = params['AMOUNT']
    words           = params['WORDS']

    @order = Order.find_by(
      id: transidmerchant,
      total: amount,
      status: 'payment_pending'
    )

    if @order.present?
      render plain: 'Continue'
    else
      render plain: 'Stop'
    end
  end

  def notify
    transidmerchant = params['TRANSIDMERCHANT']
    amount          = params['AMOUNT']
    result          = params['RESULT']

    @order = Order.find_by(
      id: transidmerchant,
      total: amount,
      status: 'payment_pending'
    )

    if result.upcase == 'SUCCESS' && @order.present?
      op = OrderProcessor.new(@order)
      op.confirm_payment_success
      op.send_ticket_to(@order.attendees)
      OrderProcessor.log_income(@order, @order.event)

      render plain: 'Continue'
    else
      render plain: 'Stop'
    end
  end

  def redirect
    transidmerchant = params['TRANSIDMERCHANT']
    @payment_method = params['PTYPE']
    @result = params['RESULT']

    @order = Order.find_by(id: transidmerchant)
    @event = @order.event
  end

  def cancel
    render plain: 'Canceled'
  end
end

app/views/payments/cancel.html.erb
<div class="order order--full">

  <div class="row">
    <div class="large-8 large-centered columns">
      <div class="order-full-logo">
        <% if @event.logo? %>
          <%= image_tag @event.logo %>
        <% else %>
          <%= image_tag 'logogram-light.png', class:'default' %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="large-8 large-centered columns">
      <h5>You have cancelled the checkout process</h5>
    </div>
  </div>

  <div class="order-full-footer static">
    <div class="trademark small-6 large-6 columns">
      <h3>Powered by</h3>
      <a href="https://www.handl.in/"><%= image_tag 'logogram-light.png', class:'logo' %></a>
    </div>

    <div class="menu small-6 large-6 columns">
      <ul>
        <li><a href="<%= terms_and_conditions_path %>">Term & Conditions</a></li>
        <li><a href="<%= privacy_policy_path %>">Privacy Policy</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/payments/notify.html.erb
<p><%= @response %></p>

app/views/payments/redirect.html.erb
<div class="order order--full">

  <div class="row">
    <div class="large-8 large-centered columns">
      <div class="order-full-logo">
        <% if @event.logo? %>
          <%= image_tag @event.logo %>
        <% else %>
          <%= image_tag 'logogram-light.png', class:'default' %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="large-8 large-centered columns">
      <h5>Thank you, you have completed the ordering process. Please check your email for payment instruction from Doku Payment. Oh and if you want to order more ticket, you can go back to the <a href="<%= event_orders_path(@event) %>">event page</a></h5>
    </div>
  </div>

  <div class="order-full-footer static">
    <div class="trademark small-6 large-6 columns">
      <h3>Powered by</h3>
      <a href="https://www.handl.in/"><%= image_tag 'logogram-light.png', class:'logo' %></a>
    </div>

    <div class="menu small-6 large-6 columns">
      <ul>
        <li><a href="<%= terms_and_conditions_path %>">Term & Conditions</a></li>
        <li><a href="<%= privacy_policy_path %>">Privacy Policy</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/payments/verify.html.erb
<p><%= @response %></p>